apiVersion: apps/v1
kind: Deployment
metadata:
  name: ama-logs-geneva-deployment
  labels:
   chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
   release: {{ .Release.Name }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      rsName: "ama-logs-geneva"
  strategy:
    type: RollingUpdate
  template:
    metadata:
     annotations:
        agentVersion: {{ .Values.image.agentVersion }}
     labels:
       rsName: "ama-logs-geneva"
       aadpodidbinding: {{ .Values.genevaLogsConfig.aadpodidbinding }}
    spec:
     {{- with .Values.affinity }}
     affinity: {{- toYaml . | nindent 8 }}
     {{- end }}
     containers:
       - name: ama-logs-geneva
         image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag }}
         imagePullPolicy: {{ .Values.image.pullPolicy }}
         resources:
          {{- toYaml .Values.resources | nindent 12 }}
         env:
         - name: GENEVA_LOGS_TELEMETRY_SERVICE_MODE
           value: "true"
         - name: CONTAINER_TYPE
           value: "geneva-container"
         - name: AZMON_CONTAINER_LOG_SCHEMA_VERSION
           value: "v2"
         - name: ClOUD_ENVIRONMENT
           value:  {{ .Values.genevaLogsConfig.environment | quote }}
         - name: MONITORING_GCS_ENVIRONMENT
           value:  {{ .Values.genevaLogsConfig.environment | quote }}
         - name: MONITORING_GCS_ACCOUNT
           value: {{ .Values.genevaLogsConfig.account | quote }}
         - name: MONITORING_GCS_NAMESPACE
           value: {{ .Values.genevaLogsConfig.namespace  | quote }}
         - name: MONITORING_CONFIG_VERSION
           value: {{ .Values.genevaLogsConfig.configversion  | quote }}
         - name: MONITORING_GCS_AUTH_ID_TYPE
           value: "AuthMSIToken"
         - name: MONITORING_GCS_AUTH_ID
           value: {{ .Values.genevaLogsConfig.authid  | quote }}
         - name: MONITORING_USE_GENEVA_CONFIG_SERVICE
           value: "true"
         - name: MONITORING_MAX_EVENT_RATE
           value: "50000" # default MDSD EPS is 20K which is not enough for large scale
         - name: FBIT_INPUT_FORWARD_BUFFER_CHUNK_SIZE
           value: "15m"
         - name: FBIT_INPUT_FORWARD_BUFFER_CHUNK_MAX_SIZE
           value: "30m"
         - name: AKS_RESOURCE_ID
           value: {{ .Values.env.clusterResourceId  | quote }}
         - name: AKS_REGION
           value: {{ .Values.env.clusterRegion  | quote }}
         - name: CONTROLLER_TYPE
           value: "DaemonSet" #  TODO - figure out what should be the right controller type here since DS being utilized here
         - name: NODE_IP
           valueFrom:
              fieldRef:
                fieldPath: status.hostIP
         ports:
         - name: http
           containerPort: 24224
           protocol: TCP
         livenessProbe:
          exec:
            command:
              - /bin/bash
              - -c
              - /opt/livenessprobe.sh
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 15
