exporters:
  file:
    path: /opt/microsoft/otelcollector/promotel.json
  influx:
    loglevel: debug
  otlp:
    endpoint: 127.0.0.1:55680
    insecure: true
receivers:
    prometheus:
      include_resource_labels: true
      config:
        scrape_configs:
        # scrape_configs must be non-null for collector to start
        - job_name: empty_job
service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [otlp]