apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: geneva-services
  name: geneva-services
spec:
  ports:
  - name: fluentbit-fwd
    port: 24224
    protocol: TCP
    targetPort: 24224
  selector:
    name: geneva-services
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-svc-config
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020
        storage.path  /var/log/flb-storage/
        storage.sync              normal
        storage.checksum          off
        storage.backlog.mem_limit 50M

    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-fwd-fluentbit.conf
    # @INCLUDE output-null.conf

  input-kubernetes.conf: |
    [INPUT]
      Name              forward
      Listen            0.0.0.0
      Port              24224
      Buffer_Chunk_Size 1M
      Buffer_Max_Size   6M


  filter-kubernetes.conf: |
    # [FILTER]
    #     Name                kubernetes
    #     Match               kube.*
    #     #Kube_URL            https://kubernetes.default.svc:443
    #     Kube_URL            https://kubernetes.default.svc.cluster.local:443
    #     Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    #     Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
    #     Kube_Tag_Prefix     kube.var.log.containers.
    #     Merge_Log           On
    #     Merge_Log_Key       log_processed
    #     Labels Off
    #     Annotations Off
    #     K8S-Logging.Parser  On
    #     K8S-Logging.Exclude On
    #     Buffer_Size         512k
    #     # Kube_meta_preload_cache_dir /var/run/kube_meta_cache
    #     # Use_Kubelet         false
    #     # Kubelet_Port        10250

    # [FILTER]
    #     Name nest
    #     Match kube.*
    #     Operation lift
    #     Nested_under kubernetes
    #     Add_prefix   kubernetes_

    # [FILTER]
    #     Name modify
    #     Match kube.*
    #     Remove kubernetes_container_image
    #     Remove kubernetes_docker_id
    #     Remove kubernetes_pod_id
    #     Remove kubernetes_host
    #     Remove kubernetes_container_hash

    # [FILTER]
    #     Name                rewrite_tag
    #     Match               kube.*
    #     Rule                $kubernetes_namespace_name ^(.*)$ cosmic.$kubernetes_namespace_name.$kubernetes_pod_name.$kubernetes_container_name.log false

  output-fwd-fluentbit.conf: |
    [OUTPUT]
      Name stdout
      Match *

  parsers.conf: |
    [PARSER]
      # http://rubular.com/r/tjUt3Awgg4
      Name cri
      Format regex
      Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$
      Time_Key    time
      Time_Format %Y-%m-%dT%H:%M:%S.%L%z
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: geneva-services
  labels:
    app: geneva-services
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: geneva-services
  template:
    metadata:
      labels:
        name: geneva-services
      annotations:
        fluentbit.io/exclude: "true"
    spec:
      nodeSelector:
        kubernetes.io/os: "linux"
      containers:
        # FluentBit
        - name: fluentbit
          image: fluent/fluent-bit:1.9
          ports:
          - name: fluentbit-fwd
            containerPort: 24224
            protocol: TCP
          volumeMounts:
            - name: fluent-bit-svc-config
              mountPath: /fluent-bit/etc/
      volumes:
        - name: fluent-bit-svc-config
          configMap:
           name: fluent-bit-svc-config
---