apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: geneva-services
  name: geneva-services-fluentd
spec:
  ports:
  - name: fluentd-fwd
    port: 24224
    protocol: TCP
    targetPort: 24224
  selector:
    name: geneva-services
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-conf
data:
  fluentd.conf: |
    # This file collects, filters and sends logs to Geneva. You should modify it according to your specific needs.
    # inputs

    <source>
      @type forward
      port 24224
    </source>

    # Everything goes to standard output
    <match **>
      @type stdout
    </match>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: geneva-services
  labels:
    app: geneva-services
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: geneva-services
  template:
    metadata:
      labels:
        name: geneva-services
      annotations:
        fluentbit.io/exclude: "true"
    spec:
      nodeSelector:
        kubernetes.io/os: "linux"
      containers:
        # FluentD
        - name: fluentd
          image: docker.io/roobasa/fluentd:master_20210928.1_proto_v0.11
          ports:
          - name: fluentd-fwd
            containerPort: 24224
            protocol: TCP
          env:
            - name: FLUENTD_CONF
              value: /etc/fluentd/fluentd.conf
          volumeMounts:
            - name: fluentd-conf-vol
              mountPath: /etc/fluentd
            - name: fluentd-buffer-vol
              mountPath: "/var/log/td-agent"
      volumes:
        - name: fluentd-conf-vol
          configMap:
            name: fluentd-conf
        - name: fluentd-buffer-vol
          emptyDir: {}
---