apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: geneva-services
  name: geneva-services
spec:
  ports:
  - name: fluentbit-fwd
    port: 24224
    protocol: TCP
    targetPort: 24224
  selector:
    name: geneva-services
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: geneva-services
  labels:
    app: geneva-services
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: geneva-services
  template:
    metadata:
      labels:
        name: geneva-services
      annotations:
        fluentbit.io/exclude: "true"
    spec:
      replicaCount: 1
      nodeSelector:
        kubernetes.io/os: "linux"
      containers:
        - name: geneva-services-svc
          image: "mcr.microsoft.com/azuremonitor/containerinsights/cidev:09292022-c60d4827"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 500m
              memory: 750Mi
            requests:
              cpu: 75m
              memory: 325Mi
          env:
            - name: ENABLE_CONTAINER_LOGS_1P
              value: "true"
            - name: CONTAINER_LOGS_1P_MODE
              value: "INGESTION"
            - name: AZMON_CONTAINER_LOG_SCHEMA_VERSION
              value: "v2"
            - name: MONITORING_GCS_ENVIRONMENT
              value: "Stage" # Supported values Test, Stage, DiagnosticsProd, FirstpartyProd, BillingProd, ExternalProd, CaMooncake, CaFairfax, CaBlackforest
            - name: MONITORING_GCS_ACCOUNT
              value: "containerlogs"
            - name: MONITORING_GCS_NAMESPACE
              value: "akscilogs"
            - name: MONITORING_CONFIG_VERSION
              value: "2.0"
            - name: MONITORING_GCS_AUTH_ID_TYPE
              value: "AuthMSIToken"
            - name: MONITORING_GCS_AUTH_ID
              value: "object_id#febeeac4-c2a9-4c53-a914-cfae18666cb9" # supported value formatss object_id#<guid> or client_id#<guid> or mi_res_id#<user-assigned managed identity resource id>
            - name: MONITORING_USE_GENEVA_CONFIG_SERVICE
              value: "true"
            # azure devops pipeline uses AKS_RESOURCE_ID and AKS_REGION hence ensure to uncomment these
            - name: AKS_RESOURCE_ID
              value: "/subscriptions/b4b0cbab-64dc-42bc-9d95-ea7c8d0cf188/resourcegroups/gangams-aks-suk/providers/Microsoft.ContainerService/managedClusters/gangams-aks-suk"
            - name: AKS_REGION
              value: "uksouth"
            - name: CONTROLLER_TYPE
              value: "DaemonSet"
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          ports:
            - name: fluentbit-fwd
              containerPort: 24224
              protocol: TCP
          securityContext:
            privileged: true
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - /opt/livenessprobe.sh
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 15
---