kind: ConfigMap
apiVersion: v1
data:
  schema-version:
    #string.used by agent to parse config. supported versions are {v1}. Configs with other schema versions will be rejected by the agent.
    v1
  config-version:
    #string.used by customer to keep track of this config file's version in their source control/repository (max allowed 10 chars, other chars will be truncated)
    ver1
  prometheus-collector-settings: |-
    [prometheus_collector_settings.default_metric_account]
      account_name = "containerinsightsgenevaaccount2"
  prometheus-config: |-
    global:
      evaluation_interval: 60s
      scrape_interval: 60s
    scrape_configs:
    - job_name: prometheus_ref_app
      scheme: http
      kubernetes_sd_configs:
        - role: service
      relabel_configs:
        - source_labels: [__meta_kubernetes_service_name]
          action: keep
          regex: "prometheus-reference-service"
metadata:
  name: prometheus-collector-configmap
  namespace: kube-system
