name: Run Unit Tests
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - ci_dev
      - ci_prod
  push:
    branches:
      - ci_dev
      - ci_prod
jobs:
  Golang-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run unit tests
        run: |
          sudo mkdir -p /var/opt/microsoft/docker-cimprov/log/
          sudo chmod 777 /var/opt/microsoft/docker-cimprov/log/
          cd ${{ github.workspace }}
          cd test/unit-tests
          export GOROOT=$GOROOT_1_15_X64
          export PATH=$GOROOT/bin:$PATH
          export PATH=/home/runner/go/bin:$PATH
          go get -u github.com/golang/mock/gomock
          go get -u golang.org/x/mod/modfile
          go get -u golang.org/x/tools/imports
          go install github.com/golang/mock/mockgen
          ./run_go_tests.sh
  Ruby-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: install fluent
        run: |
          sudo gem install fluentd -v "1.14.2" --no-document
          sudo fluentd --setup ./fluent
      - name: Run unit tests
        run: |
          cd ${{ github.workspace }}
          ./test/unit-tests/run_ruby_tests.sh
